import { useI18n } from '../i18n'

const en = {
  connected: 'Your world. Connected.',
  heroFirst: 'Money moves.',
  heroSecond: 'Connection stays.',
  intro: 'A more personal way to send money across the globe.',
  watch: 'Watch the film',
  filmTitle: 'A little closer.',
  filmLabel: 'THE XPRESSTEND FILM',
  play: 'Play the XpressTend film',
  experience: 'The experience',
  personal: 'Made for real life',
  experienceTitle: 'Your people.\nAlways within reach.',
  send: 'Send',
  people: 'People',
  activity: 'Activity',
  sendTitle: 'A thoughtful way to send.',
  sendBody:
    'Choose an amount, see the details, and take the next step with confidence.',
  peopleTitle: 'Start with someone.',
  peopleBody:
    'Keep the people you send to close. Find a familiar name and pick up where you left off.',
  activityTitle: 'Follow every step.',
  activityBody:
    'Keep your transfers in view, with the details there when you need them.',
  ratesEyebrow: 'Every detail, in view',
  ratesTitle: 'A little clarity.\nA lot of confidence.',
  ratesBody:
    'Explore the amount, destination, and fee before you take the next step.',
  downloadTitle: 'Your world.\nIn your pocket.',
  downloadBody: 'The same thoughtful experience, wherever life takes you.',
  android: 'XpressTend for Android',
  androidNote: 'Coming soon',
  ios: 'XpressTend for iPhone',
  iosNote: 'Coming soon',
  notifyMe: 'Email me when it is ready',
  web: 'Or explore it in your browser',
  installHelp: 'Installing on Android',
  installBody:
    'Open the downloaded APK on your Android phone. If asked, allow installation from this source in your device settings.',
  availability: 'Payment availability',
  availabilityBody:
    'Payments currently run in test mode. No customer funds are moved.',
  back: 'Back to website',
  exploreLabel: 'Explore mode · Sample data',
  exit: 'Leave explore mode',
  shellTitle: 'A little closer.\nWith every tap.',
  shellBody: 'Your people, your transfers, your world. All in one place.',
  skip: 'Skip to content',
  filmDescription:
    'A globe connects people across distances. In XpressTend, a person chooses a recipient, enters an amount, and sees a transfer confirmation. Closer, wherever life takes you.',
} as const

type Copy = { [K in keyof typeof en]: string }
const so: Copy = {
  connected: 'Dunidaada. Isku xiran.',
  heroFirst: 'Lacagtu way gudubtaa.',
  heroSecond: 'Xiriirku wuu joogaa.',
  intro: 'Hab kuu dhow oo aad lacag ugu dirto dunida oo dhan.',
  watch: 'Daawo muuqaalka',
  filmTitle: 'Wax yar isu soo dhowaada.',
  filmLabel: 'MUUQAALKA XPRESSTEND',
  play: 'Daar muuqaalka XpressTend',
  experience: 'Khibradda',
  personal: 'Noloshaada loogu talagalay',
  experienceTitle: 'Dadkaaga.\nMar walba kuu dhow.',
  send: 'Dir',
  people: 'Dadka',
  activity: 'Dhaqdhaqaaqa',
  sendTitle: 'Hab fudud oo wax lagu diro.',
  sendBody:
    'Dooro lacagta, eeg faahfaahinta, oo tallaabada xigta qaad adigoo hubinaya.',
  peopleTitle: 'Ka bilow qofkaaga.',
  peopleBody:
    'Dadka aad lacagta u dirto kuu dhowee. Magac aad taqaan raadi oo sii wad.',
  activityTitle: 'La soco tallaabo kasta.',
  activityBody: 'Xawaaladahaaga iyo faahfaahintooda eeg marka aad u baahato.',
  ratesEyebrow: 'Faahfaahin kasta waa muuqataa',
  ratesTitle: 'Wax walba ha kuu caddaadaan.',
  ratesBody:
    'Eeg lacagta, meesha loo dirayo iyo khidmadda ka hor tallaabada xigta.',
  downloadTitle: 'Dunidaada.\nJeebkaaga ku jirta.',
  downloadBody: 'Khibrad kuu dhow, meel kasta oo aad joogto.',
  android: 'XpressTend ee Android',
  androidNote: 'Dhawaan',
  ios: 'XpressTend ee iPhone',
  iosNote: 'Dhawaan',
  notifyMe: 'I email marka ay diyaar noqoto',
  web: 'Ama ku tijaabi biraawsarkaaga',
  installHelp: 'Ku rakibidda Android',
  installBody:
    'Fur APK-ga aad soo dejisay. Haddii lagu weydiiyo, oggolow rakibidda ishan ee dejimaha taleefanka.',
  availability: 'Helitaanka lacag-bixinta',
  availabilityBody:
    'Lacag-bixintu waxay ku jirtaa hab tijaabo. Lacag macaamiil lama wareejiyo.',
  back: 'Ku noqo bogga',
  exploreLabel: 'Habka sahaminta · Xog tusaale ah',
  exit: 'Ka bax sahaminta',
  shellTitle: 'Isu soo dhowaada.\nTaabasho kasta.',
  shellBody: 'Dadkaaga, xawaaladahaaga, dunidaada. Hal meel.',
  skip: 'U gudub nuxurka',
  filmDescription:
    'Dunidu waxay isku xiraysaa dad kala fog. Qof ayaa doorta qaate, geliya lacagta, kadibna arka xaqiijinta xawaaladda.',
}
const es: Copy = {
  connected: 'Su mundo. Conectado.',
  heroFirst: 'El dinero se mueve.',
  heroSecond: 'El vínculo permanece.',
  intro: 'Una forma más personal de enviar dinero por el mundo.',
  watch: 'Ver el vídeo',
  filmTitle: 'Un poco más cerca.',
  filmLabel: 'EL VÍDEO DE XPRESSTEND',
  play: 'Reproducir el vídeo de XpressTend',
  experience: 'La experiencia',
  personal: 'Pensado para la vida real',
  experienceTitle: 'Su gente.\nSiempre cerca.',
  send: 'Enviar',
  people: 'Personas',
  activity: 'Actividad',
  sendTitle: 'Una forma de enviar con confianza.',
  sendBody:
    'Elija el importe, revise los detalles y dé el siguiente paso con confianza.',
  peopleTitle: 'Empiece por alguien.',
  peopleBody:
    'Tenga cerca a quienes envía dinero. Encuentre un nombre conocido y continúe.',
  activityTitle: 'Siga cada paso.',
  activityBody:
    'Consulte sus transferencias y sus detalles cuando los necesite.',
  ratesEyebrow: 'Cada detalle, a la vista',
  ratesTitle: 'Más claridad.\nMás confianza.',
  ratesBody:
    'Consulte el importe, el destino y la comisión antes de continuar.',
  downloadTitle: 'Su mundo.\nEn su bolsillo.',
  downloadBody: 'La misma experiencia cuidada, vaya donde vaya.',
  android: 'XpressTend para Android',
  androidNote: 'Muy pronto',
  ios: 'XpressTend para iPhone',
  iosNote: 'Muy pronto',
  notifyMe: 'Avísenme cuando esté listo',
  web: 'O explórela en su navegador',
  installHelp: 'Instalar en Android',
  installBody:
    'Abra el APK descargado en su teléfono Android. Si se le solicita, permita la instalación desde esta fuente en los ajustes.',
  availability: 'Disponibilidad de pagos',
  availabilityBody:
    'Los pagos funcionan actualmente en modo de prueba. No se transfieren fondos de clientes.',
  back: 'Volver al sitio web',
  exploreLabel: 'Modo exploración · Datos de ejemplo',
  exit: 'Salir del modo exploración',
  shellTitle: 'Un poco más cerca.\nCon cada toque.',
  shellBody: 'Su gente, sus transferencias, su mundo. Todo en un solo lugar.',
  skip: 'Ir al contenido',
  filmDescription:
    'Un globo conecta a personas a distancia. Una persona elige un destinatario, introduce un importe y ve una confirmación en XpressTend.',
}
const pt: Copy = {
  connected: 'Seu mundo. Conectado.',
  heroFirst: 'O dinheiro se move.',
  heroSecond: 'A conexão fica.',
  intro: 'Uma forma mais pessoal de enviar dinheiro pelo mundo.',
  watch: 'Assista ao filme',
  filmTitle: 'Um pouco mais perto.',
  filmLabel: 'O FILME DA XPRESSTEND',
  play: 'Reproduzir o filme da XpressTend',
  experience: 'A experiência',
  personal: 'Feito para a vida real',
  experienceTitle: 'Suas pessoas.\nSempre por perto.',
  send: 'Enviar',
  people: 'Pessoas',
  activity: 'Atividade',
  sendTitle: 'Uma forma cuidadosa de enviar.',
  sendBody:
    'Escolha o valor, confira os detalhes e dê o próximo passo com confiança.',
  peopleTitle: 'Comece por alguém.',
  peopleBody:
    'Mantenha por perto as pessoas para quem você envia. Encontre um nome conhecido e continue.',
  activityTitle: 'Acompanhe cada passo.',
  activityBody: 'Veja suas transferências e os detalhes sempre que precisar.',
  ratesEyebrow: 'Cada detalhe à vista',
  ratesTitle: 'Mais clareza.\nMais confiança.',
  ratesBody: 'Confira o valor, o destino e a tarifa antes de continuar.',
  downloadTitle: 'Seu mundo.\nNo seu bolso.',
  downloadBody: 'A mesma experiência cuidadosa, onde quer que você esteja.',
  android: 'XpressTend para Android',
  androidNote: 'Em breve',
  ios: 'XpressTend para iPhone',
  iosNote: 'Em breve',
  notifyMe: 'Avise-me quando estiver pronto',
  web: 'Ou explore no seu navegador',
  installHelp: 'Instalar no Android',
  installBody:
    'Abra o APK baixado no seu Android. Se solicitado, permita a instalação dessa fonte nas configurações do aparelho.',
  availability: 'Disponibilidade de pagamentos',
  availabilityBody:
    'Os pagamentos estão em modo de teste. Nenhum valor de clientes é movimentado.',
  back: 'Voltar ao site',
  exploreLabel: 'Modo de exploração · Dados de exemplo',
  exit: 'Sair do modo de exploração',
  shellTitle: 'Um pouco mais perto.\nA cada toque.',
  shellBody:
    'Suas pessoas, suas transferências, seu mundo. Tudo em um só lugar.',
  skip: 'Ir para o conteúdo',
  filmDescription:
    'Um globo conecta pessoas à distância. Uma pessoa escolhe um destinatário, informa um valor e vê uma confirmação na XpressTend.',
}
const ar: Copy = {
  connected: 'عالمك. متصل.',
  heroFirst: 'المال ينتقل.',
  heroSecond: 'والصلة تبقى.',
  intro: 'طريقة أقرب إليك لإرسال الأموال حول العالم.',
  watch: 'شاهد الفيديو',
  filmTitle: 'أقرب بقليل.',
  filmLabel: 'فيديو XPRESSTEND',
  play: 'تشغيل فيديو XpressTend',
  experience: 'التجربة',
  personal: 'مصمم للحياة اليومية',
  experienceTitle: 'أحباؤك.\nدائماً بالقرب منك.',
  send: 'إرسال',
  people: 'الأشخاص',
  activity: 'النشاط',
  sendTitle: 'طريقة مدروسة للإرسال.',
  sendBody: 'اختر المبلغ، وراجع التفاصيل، واتخذ الخطوة التالية بثقة.',
  peopleTitle: 'ابدأ بمن يهمك.',
  peopleBody: 'أبقِ الأشخاص الذين ترسل إليهم قريبين. ابحث عن اسم مألوف وتابع.',
  activityTitle: 'تابع كل خطوة.',
  activityBody: 'اطّلع على تحويلاتك وتفاصيلها متى احتجت إليها.',
  ratesEyebrow: 'كل التفاصيل أمامك',
  ratesTitle: 'وضوح أكثر.\nثقة أكبر.',
  ratesBody: 'راجع المبلغ والوجهة والرسوم قبل المتابعة.',
  downloadTitle: 'عالمك.\nفي جيبك.',
  downloadBody: 'التجربة المدروسة نفسها، أينما أخذتك الحياة.',
  android: 'XpressTend لأندرويد',
  androidNote: 'قريبًا',
  ios: 'XpressTend لآيفون',
  iosNote: 'قريبًا',
  notifyMe: 'أبلغوني عند الجهوزية',
  web: 'أو استكشفه في متصفحك',
  installHelp: 'التثبيت على أندرويد',
  installBody:
    'افتح ملف APK الذي نزّلته. اسمح بالتثبيت من هذا المصدر في إعدادات جهازك إذا طُلب منك ذلك.',
  availability: 'إتاحة المدفوعات',
  availabilityBody:
    'تعمل المدفوعات حالياً في وضع الاختبار. لا يتم تحويل أموال العملاء.',
  back: 'العودة إلى الموقع',
  exploreLabel: 'وضع الاستكشاف · بيانات تجريبية',
  exit: 'مغادرة وضع الاستكشاف',
  shellTitle: 'أقرب بقليل.\nمع كل لمسة.',
  shellBody: 'أحباؤك وتحويلاتك وعالمك. كل ذلك في مكان واحد.',
  skip: 'الانتقال إلى المحتوى',
  filmDescription:
    'كرة أرضية تصل بين أشخاص متباعدين. يختار شخص مستلماً ويدخل مبلغاً ثم يرى تأكيد التحويل في XpressTend.',
}
export function useBrandCopy(): Copy {
  const { lang } = useI18n()
  return { en, so, es, 'pt-BR': pt, ar }[lang]
}
